[BallPlacementAvoid]
ball_placement_avoid_speed = 1.5

[DefendGoalOnCircle]
defend_goal_circle_enemy_threshold = 0.5
defend_goal_circle_line_goal_cutoff = 0.313
defend_goal_circle_weight = 0.419
goal_threshold = 3.0

[GeneralSkills]
defense_area_buffer = 0.25

[GoalieIntercept]
goalie_intercept_goal_distance = 0.5

[KickBallThroughTarget]
kick_ball_through_target_preposition_angle = 0.2

[Oktoskill]
okto_skill_speed = 1.0

[PassBallToRobot]
kick_vel_multiplier = 0.22
kick_vel_offset = 2.788

[ReceiveBall]
receive_ball_kg = 0.055
receive_ball_kv = 0.016

[getBall]
get_ball_robot_radius = 0.035

[robot]
robot_vel_max_theta_turn_around_ball = 0.25